### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by maheshsetti** [iyu/excel2json#1]
thnaks for great work. it will be very usefull

/node_modules/excel2json/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 /node_modules/excel2json/node_modules/libxmljs/build/xmljs.node

i followed your guidance.. but i got above error so plz fix it as early as possible.

**Comment by iyu** [comment]
Please try this.
```sh
$ npm install libxmljs
$ node -e "require('libxmljs')"
$ echo $?
0
```

If become Error, I think it is caused by your environment. 
Could you tell me your node version and OS your are using?

**Comment by maheshsetti** [comment]
echo $?
i got 0

my npm 2.5.1
node v0.12.0
OS: Ubuntu 14.04 LTS

how can i solve?

**Comment by iyu** [comment]
Does `/node_modules/excel2json/node_modules/libxmljs/build/Release/xmljs.node` exist?
I in the environment has been generated in this position.

sorry, I can not understand why is happening is an error.

**Comment by maheshsetti** [comment]
+10000000000000000000000000000000000000000000000000000

thanks a lot buddy, problem with libxmljs i reinstalled it. now working fine.
