### ISSUE TITLE
can i change input excel formate to regular excel format

### ISSUE THREAD

**Issue by maheshsetti** [iyu/excel2json#2]
i have to change excel format. is it possible to do?

**Comment by maheshsetti** [comment]
required excel format is
           A           B          C              D            E             F             G   ...
1       title1     title2      title3         title4       title5        title6        title7  .. 
2     data21   data22   data23     data24    data25     data26   data27...
3     data31   data32   data33    data34    data35    data36     data37...
4     data41   data42   data43     data44     data45     data46      data47...
5     data51   data52   data53     data54     data55     data56      data57...
6     data61   data62   data63     data64     data65     data66      data67...
.
.
.

**Comment by iyu** [comment]
This library was created to represent the json data in Excel.
So changes to this format is difficult.

But what it is to use the [xlsx-parser](https://github.com/iyu/xlsx-parser) If you only read the Excel data?

**Comment by iyu** [comment]
It is possible with the set if you just want to erase the blank line.
```js
var excel2json = require('excel2json');
excel2json.setup({
    option_cell: 'A1', // Cell with a custom sheet option. It is not yet used now. (default: 'A1'
    attr_line: '2',    // Line with a data attribute. (default: '2'
    data_line: '3',    // Line with a data. (default: '4'
});
```
However, the following format is the minimum.

|  | A | B | C | D |
|:-:|--:|--:|--:|--:|
|1|{ }| | | |
|2|attr1|attr2|attr3|attr4|
|3|data11|data12|data13|data14|
|4|data21|data22|data23|data24|

**Comment by maheshsetti** [comment]
+1000000000
thanks for explaination.

**Comment by iyu** [comment]
@maheshsetti This format also was possible.
Setting is here.

```js
var excel2json = require('excel2json');
excel2json.setup({
    option_cell: null, // Cell with a custom sheet option. It is not yet used now. (default: 'A1'
    attr_line: 1,    // Line with a data attribute. (default: 2
    data_line: 2,    // Line with a data. (default: 4
    ref_key: 'title1'     // ref key. (default: '_id'
});
```

test.xlsx

|  | A | B | C | D |
|:-:|--:|--:|--:|--:|
|1|title1|title2|title3|title4|
|2|data11|data12|data13|data14|
|3|data21|data22|data23|data24|

```js
excel2json.parse('./test.xlsx', [1], function(err, result) {
  console.log('--parse result--')
  console.log(JSON.stringify(result, null, 2));
  excel2json.toJson(result, function(err, result) {
    console.log('--toJson result--');
    console.log(result);
  });
});

```
```js
--parse result--
[
  {
    "num": 1,
    "name": "Sheet1",
    "opts": {
      "attr_line": 1,
      "data_line": 2,
      "ref_key": "title1",
      "format": {
        "A": {
          "type": null,
          "key": "title1",
          "keys": [
            "title1"
          ]
        },
        "B": {
          "type": null,
          "key": "title2",
          "keys": [
            "title2"
          ]
        },
        "C": {
          "type": null,
          "key": "title3",
          "keys": [
            "title3"
          ]
        },
        "D": {
          "type": null,
          "key": "title4",
          "keys": [
            "title4"
          ]
        }
      }
    },
    "list": [
      {
        "title1": "data11",
        "title2": "data12",
        "title3": "data13",
        "title4": "data14"
      },
      {
        "title1": "data21",
        "title2": "data22",
        "title3": "data23",
        "title4": "data24"
      }
    ]
  }
]
--toJson result--
{ Sheet1:
   { data11:
      { title1: 'data11',
        title2: 'data12',
        title3: 'data13',
        title4: 'data14' },
     data21:
      { title1: 'data21',
        title2: 'data22',
        title3: 'data23',
        title4: 'data24' } } }
```

**Comment by maheshsetti** [comment]
thank you, i have done this :D
